// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeqdWSg5IVmJgtatrIFBekxP-vAP9mtdE',
    appId: '1:731524551717:web:2050d1394a7736725fdbcc',
    messagingSenderId: '731524551717',
    projectId: 'developments-checker',
    authDomain: 'developments-checker.firebaseapp.com',
    storageBucket: 'developments-checker.firebasestorage.app',
    measurementId: 'G-B5MPCZ6QDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDNMqMC_vEsBdZyjqM2geWvB9_oj9AIYw',
    appId: '1:731524551717:android:c3394f062d6513ce5fdbcc',
    messagingSenderId: '731524551717',
    projectId: 'developments-checker',
    storageBucket: 'developments-checker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4eSsHKtxNPCrok8Nha0TTWLaxfOhplkQ',
    appId: '1:731524551717:ios:37ac35eba9ed04d05fdbcc',
    messagingSenderId: '731524551717',
    projectId: 'developments-checker',
    storageBucket: 'developments-checker.firebasestorage.app',
    iosBundleId: 'com.example.cateringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4eSsHKtxNPCrok8Nha0TTWLaxfOhplkQ',
    appId: '1:731524551717:ios:37ac35eba9ed04d05fdbcc',
    messagingSenderId: '731524551717',
    projectId: 'developments-checker',
    storageBucket: 'developments-checker.firebasestorage.app',
    iosBundleId: 'com.example.cateringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeqdWSg5IVmJgtatrIFBekxP-vAP9mtdE',
    appId: '1:731524551717:web:e8f8e5036d6b72e55fdbcc',
    messagingSenderId: '731524551717',
    projectId: 'developments-checker',
    authDomain: 'developments-checker.firebaseapp.com',
    storageBucket: 'developments-checker.firebasestorage.app',
    measurementId: 'G-7T0E10F5D1',
  );
}
